# Generated by Django 5.2.1 on 2025-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_data',
            fields=[
                ('sensor_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sensor_timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.JSONField(verbose_name='')),
                ('readings', models.JSONField(verbose_name='')),
                ('alert_level', models.CharField(max_length=20)),
                ('battery_level', models.FloatField()),
                ('network_signal', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
