# Generated by Django 5.2.1 on 2025-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_data',
            name='network_signal',
        ),
        migrations.AddField(
            model_name='sensor_data',
            name='network_status',
            field=models.CharField(default='2G', max_length=20),
        ),
    ]
