# Generated by Django 5.2.1 on 2025-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sensor_data_network_signal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
